### ISSUE TITLE
Reopen #1

### ISSUE THREAD

**Issue by panwarab** [coding-blocks/shortlr_android_app#11]
Reopening #1 addressed by [PR](https://github.com/coding-blocks/shortlr_android_app/pull/10)

**Comment by panwarab** [comment]
@piyush0  There are merge conflicts. Any way around?

**Comment by piyush0** [comment]
I was getting conflicts in widget_layout.xml
Check if you can fix that

**Comment by panwarab** [comment]
Need to fetch the new updates for that.

**Comment by panwarab** [comment]
working on it,
