### ISSUE TITLE
Options window not getting closed on home button press.

### ISSUE THREAD

**Issue by panwarab** [coding-blocks/shortlr_android_app#14]
screencast:-

![shrtlr_issue_gif](https://cloud.githubusercontent.com/assets/5828500/26081918/b095b628-39ea-11e7-9277-844e9b488f1d.gif)

**Comment by panwarab** [comment]
@piyush0 Please mention a bounty for the issue.

**Comment by mkmar01** [comment]
@piyush0 may I work on this issue

**Comment by piyush0** [comment]
Sure go ahead.

**Comment by panwarab** [comment]
@piyush0 Need to add changes for task button and back button also. Should the bounty be increased or a new issue should be opened for it?

**Comment by piyush0** [comment]
Solved by @AbhirojPanwar in #15
