### ISSUE TITLE
Options window not getting closed on tab and back button press.

### ISSUE THREAD

**Issue by piyush0** [coding-blocks/shortlr_android_app#17]

**Comment by panwarab** [comment]
@piyush0 working on it.

**Comment by panwarab** [comment]
@piyush0 back-key is already a part of UI, so it is necessary to map it with the nav-bar back key.

**Comment by piyush0** [comment]
Yes it is necessary to close the window on back press.

**Comment by piyush0** [comment]
Solved by @AbhirojPanwar in #19
