### ISSUE TITLE
[Functionality] Write URL on the widget itself

### ISSUE THREAD

**Issue by panwarab** [coding-blocks/shortlr_android_app#21]
Current Behaviour: user can not write a link in the widget, the link can only be picked-up while a copy task is initiated (i.e. Clipboard Manager)

Additional Behaviour (Suggested): allowing the user to write the URL on the widget itself and then apply shrink to it.

**Comment by piyush0** [comment]
Are you sure it would be possible? App widgets only support remote views and edit text is not supported. How will you achieve this?

**Comment by panwarab** [comment]
@piyush0  Then it can not be done in this manner. I did not know of that though. :)
