### ISSUE TITLE
Add License to the Project

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/shortlr_android_app#28]
This project does not have a License. Needs to be added.

**Comment by jddeep** [comment]
@championswimmer @piyush0 @prateek27 @abhishek97 @sarthak-1998 Can I work on this?

**Comment by sarthak-1998** [comment]
@aggarwalpulkit596 Please check

**Comment by championswimmer** [comment]
Having a license is not necessarily needed for a project. This is an unlicensed project.
